routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', 'PageController@index');

// Auth
Auth::routes(['register' => false]);
Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    // Dashboard
    Route::get('', 'AdminController@dashboard')->name('dashboard');

    // Types
    Route::resource('types', 'TypeController');

    // Requirements
    Route::resource('requirements', 'RequirementController');

    // Items
    Route::resource('items', 'ItemController');
});

resources/views/admin/components/modals/delete-confirmation.blade.php
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content p-2">

      <div class="modal-body">

        <div class="d-flex flex-column justify-content-center align-items-center">
          <h5 class="modal-title">
            Are you sure you want to delete this?
          </h5>
          <div class="mt-4">
            <form method="POST">
              @method('DELETE')
              @csrf
              <button type="button" class="btn btn-link text-decoration-none" data-dismiss="modal">Cancel</button>
              <button-submit text="Delete" class="btn-danger"/>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

resources/views/admin/components/modals/item-create.blade.php
<div class="modal fade" id="addItemModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form method="POST" action="{{ route('admin.items.store') }}" class="m-0">
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="addItemTitle">Add Item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            {{-- Type Id --}}
            <input type="hidden" id="requirement_id" name="requirement_id" value="{{ $requirement->id }}">

            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Type</label>
              <p class="font-weight-bold"> {{ $requirement->type->name }} </p>
            </div>
            
            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Requirement</label>
              <p class="font-weight-bold"> {{ $requirement->description }} </p>
            </div>

            {{-- Item Label --}}
            <div class="form-group">
              <label for="inputItemLabel" class="bmd-label-floating">Label</label>
              <input type="text" class="form-control" id="inputItemLabel" name="type" required>
            </div>

            {{-- Description Name --}}
            <div class="form-group">
              <label for="inputItemDescription" class="bmd-label-floating">Description</label>
              <textarea type="text" class="form-control" id="inputItemDescription" name="description"></textarea>
            </div>

            {{-- Price --}}
            <div class="form-group">
              <label for="inputItemValue" class="bmd-label-floating">Value</label>
              <input type="number" min="0" class="form-control" id="inputItemValue" name="value" min="0">
            </div>
            
            {{-- Icon Name --}}
            <div class="form-group">
              <label for="inputItemIcon" class="bmd-label-floating">Icon</label>
              <textarea type="text" class="form-control" id="inputItemIcon" name="src"></textarea>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button-submit text="Add" class="btn-outline-success"/>
        </div>
      </form>
    </div>
  </div>
</div>
{{-- End Modal --}}

resources/views/admin/components/modals/item-edit.blade.php
<div class="modal fade" id="editItemModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form id="modalForm" method="POST">
        @method('PUT')
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="editItemTitle">Edit item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          {{-- Type Id --}}
          <input type="hidden" id="requirement_id" name="requirement_id" value="">

          {{-- Item Label --}}
          <div class="form-group">
            <label for="inputItemLabel" class="bmd-label-floating">Label</label>
            <input type="text" class="form-control" id="inputItemLabel" name="type" required>
          </div>

          {{-- Description Name --}}
          <div class="form-group">
            <label for="inputItemDescription" class="bmd-label-floating">Description</label>
            <textarea type="text" class="form-control" id="inputItemDescription" name="description"></textarea>
          </div>

          {{-- Price --}}
          <div class="form-group">
            <label for="inputItemValue" class="bmd-label-floating">Value</label>
            <input type="number" min="0" class="form-control" id="inputItemValue" name="value" min="0">
          </div>

          {{-- Icon Name --}}
          <div class="form-group">
            <label for="inputItemIcon" class="bmd-label-floating">Icon</label>
            <textarea type="text" class="form-control" id="inputItemIcon" name="src"></textarea>
          </div>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-outline-success">Edit</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/admin/components/modals/requirement-create.blade.php
{{-- Add Type Modal --}}
<div class="modal fade" id="addRequirementModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form method="POST" action="{{ route('admin.requirements.store') }}" class="m-0">
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="addTypeTitle">Add Requirement</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          
            {{-- Type Id --}}
            <input type="hidden" id="type_id" name="type_id" value="{{ $type->id }}">

            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Type</label>
              <p class="font-weight-bold"> {{ $type->name }} </p>
            </div>

            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Description</label>
              <input type="text" class="form-control" id="inputDescription" name="description" required>
              <small class="form-text text-muted">Question that you want to ask</small>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-outline-success">Add</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/admin/components/modals/requirement-edit.blade.php
<div class="modal fade" id="editRequirementModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form id="modalForm" method="POST">
        @method('PUT')
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="editRequirementTitle">Edit requirement</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            {{-- Requirement Id --}}
            <input type="hidden" id="type_id" name="type_id" value="">

            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Description</label>
              <input type="text" class="form-control" id="inputDescription" name="description" required>
              <small class="form-text text-muted">Question that you want to ask</small>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-outline-success">Edit</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/admin/components/modals/type-create.blade.php
<div class="modal fade" id="addTypeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form method="POST" action="{{ route('admin.types.store') }}" class="m-0">
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="addTypeTitle">Add Type</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            {{-- Name --}}
            <div class="form-group">
              <label for="inputName" class="bmd-label-floating">Name</label>
              <input type="text" class="form-control" id="inputName" name="name" required>
            </div>
            
            <div class="form-group">
              <label for="inputDescription" class="bmd-label-floating">Description</label>
              <input type="text" class="form-control" id="inputDescription" name="description" required>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-outline-success">Add</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/admin/components/modals/type-edit.blade.php
<div class="modal fade" id="editTypeModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form id="modalForm" method="POST">
        @method('PUT')
        @csrf
        <div class="modal-header">
          <h5 class="modal-title" id="editTypeTitle">Edit type</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          
          {{-- Name --}}
          <div class="form-group">
            <label for="inputName" class="bmd-label-floating">Name</label>
            <input type="text" class="form-control" id="inputName" name="name" required>
          </div>

          <div class="form-group">
            <label for="inputDescription" class="bmd-label-floating">Description</label>
            <input type="text" class="form-control" id="inputDescription" name="description" required>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-outline-success">Edit</button>
        </div>
      </form>
    </div>
  </div>
</div>