routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', 'PageController@index');

// Auth
Auth::routes(['register' => false]);
Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    // Dashboard
    Route::get('', 'AdminController@dashboard')->name('dashboard');

    // Types
    Route::resource('types', 'TypeController');

    // Requirements
    Route::resource('requirements', 'RequirementController');

    // Items
    Route::resource('items', 'ItemController');
});

resources/views/admin/components/alerts.blade.php
{{-- status alerts --}}
@if(session('status'))
  <div class="alert alert-admin alert-success alert-dismissible fade show">
    <div class="d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          {{ session('status') }}
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif
{{-- primary alerts --}}
@if(session('primary'))
  <div class="alert alert-admin alert-primary alert-dismissible fade show">
    <div class="d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          {{ session('primary') }}
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif
{{-- success alerts --}}
@if(session('success'))
  <div class="alert alert-admin alert-success alert-dismissible fade show">
    <div class="d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          {{ session('success') }}
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif
{{-- warning alerts --}}
@if(session('warning'))
  <div class="alert alert-admin alert-warning alert-dismissible fade show">
    <div class="d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          {{ session('warning') }}
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif
{{-- danger alerts --}}
@if(session('danger'))
  <div class="alert alert-admin alert-danger alert-dismissible fade show">
    <div class="d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          {{ session('danger') }}
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif
{{-- error alerts --}}
@if($errors->any())
  <div class="alert alert-admin alert-danger alert-dismissible fade show">
    <div class="container d-flex align-content-center">
      <div class="w-100 py-2">
        <p class="mb-0">
          @foreach ($errors->all() as $error)
            {{ $error }}
            <br>
          @endforeach
        </p>
      </div>
      <button type="button" class="btn" data-dismiss="alert" aria-label="Close">
        <span class="material-icons" aria-hidden="true">close</span>
      </button>
    </div>
  </div>
@endif

resources/views/admin/components/items-card.blade.php
<card-basic title="Choices" class="mt-4">
  <template v-slot:options>
    <options-dropdown>
      <button type="button" class="dropdown-item" data-toggle="modal" data-target="#addrequirementModal">
        Add Requirement
      </button>
    </options-dropdown>
  </template>
  <template v-slot:image>
    <div class="table-responsive table-hover">
      <table class="table table-hover text-truncate text-center m-0">
        <thead>
          <tr>
            <th scope="col">Item Label</th>
            <th scope="col">Description</th>
            <th scope="col">Value</th>
            <th scope="col">Icon</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody class="text-wrap align-items-center">
          @foreach($requirement->items as $item)
            <tr>
              <td class="align-middle">
                {{$item->type}}
              </td>
              <td class="align-middle w-50">
                {{$item->description}}
              </td>
              <td class="align-middle">
                {{$item->value}}
              </td>
              <td  class="w-25">
                <img class="rounded-circle img-fluid w-25" src="{{$item->src}}">
              </td>
              <td class="align-middle">
                <options-dropdown icon="more_horiz">
                  <button
                    class="dropdown-item" type="button"
                    data-toggle="modal"
                    data-target="#editItemModal"
                    data-item="{{$item}}">
                    <i class="material-icons material-icons-outlined text-dark mr-2">edit</i>
                    Edit
                  </button>
                  <button 
                    class="dropdown-item text-danger" type="button"
                    data-toggle="modal"
                    data-target="#deleteConfirmationModal"
                    data-action="{{ route('admin.items.destroy', ['item' => $item->id]) }}">
                    <i class="material-icons material-icons-outlined text-danger mr-2 w-25">delete_outlined</i>
                    Delete
                </button>
                </options-dropdown>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </template>
  <template v-slot:footer>
    <button type="button" class="btn btn-primary btn-raised float-right" data-toggle="modal" data-target="#addItemModal">
      Add Item
    </button>
  </template>
</card-basic>

resources/views/admin/components/requirements-card.blade.php
<card-basic title="Requirements" class="mt-4">
  <template v-slot:options>
    <options-dropdown>
      <button type="button" class="dropdown-item" data-toggle="modal" data-target="#addrequirementModal">
        Add Requirement
      </button>
    </options-dropdown>
  </template>
  <template v-slot:image>
    <div class="table-responsive table-hover">
      <table class="table table-hover text-truncate text-center m-0">
        <thead>
          <tr>
            <th scope="col">Description</th>
            <th scope="col">Choices</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody class="text-wrap align-items-center">
          @foreach($type->requirements as $requirement)
            <tr>
              <td> {{ $requirement->description }} </td>
              <td>
                <a href="{{ route('admin.requirements.show',['requirement' => $requirement->id]) }}" > Show choices </a>
              </td>
              <td>
                <options-dropdown icon="more_horiz">
                  <button 
                    class="dropdown-item" type="button"
                    data-toggle="modal"
                    data-target="#editRequirementModal"
                    data-requirement="{{$requirement}}">
                    <i class="material-icons material-icons-outlined text-dark mr-2">edit</i>
                    Edit
                  </button>
                  <button 
                    class="dropdown-item text-danger" type="button"
                    data-toggle="modal"
                    data-target="#deleteConfirmationModal"
                    data-action="{{ route('admin.requirements.destroy', ['requirement' => $requirement->id]) }}">
                    <i class="material-icons material-icons-outlined text-danger mr-2 w-25">delete_outlined</i>
                    Delete
                </button>
                </options-dropdown>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </template>
  <template v-slot:footer>
    <button type="button" class="btn btn-primary btn-raised float-right" data-toggle="modal" data-target="#addRequirementModal">
      Add Requirement
    </button>
  </template>
</card-basic>

resources/views/admin/components/types-card.blade.php
<card-basic title="Types" class="mt-4">
  <template v-slot:image>
    <div class="table-responsive">
      <table class="table table-hover text-truncate text-center m-0">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody class="text-wrap align-items-center">
          @foreach($types as $type)
            <tr>
              <td>
                <a href="{{ route('admin.types.show', ['type' => $type->id]) }}"> {{ $type->name }} </a>
              </td>
              <td>
                {{ $type->description }}
              </td>
              <td>
                <options-dropdown icon="more_horiz">
                  <button 
                    class="dropdown-item" type="button"
                    data-toggle="modal"
                    data-target="#editTypeModal"
                    data-type="{{$type}}">
                    <i class="material-icons material-icons-outlined text-dark mr-2">edit</i>
                    Edit
                  </button>
                  <button 
                    class="dropdown-item text-danger" type="button"
                    data-toggle="modal"
                    data-target="#deleteConfirmationModal"
                    data-action="{{ route('admin.types.destroy', ['type' => $type->id]) }}">
                    <i class="material-icons material-icons-outlined text-danger mr-2 w-25">delete_outlined</i>
                    Delete
                </button>
                </options-dropdown>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </template>
  <template v-slot:footer>
    <button type="button" class="btn btn-primary btn-raised float-right" data-toggle="modal" data-target="#addTypeModal">
      Add Type
    </button>
  </template>
</card-basic>